# Guition ESP32-P4-JC4880P443 Immich Frame
substitutions:
  name: "immich-frame-43inch"
  friendly_name: "Immich Frame 43inch"

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Packages
packages:
  espframe:
    url: https://github.com/bekdan1988/espframe
    files: [devices/guition-esp32-p4-jc4880p443/packages.yaml]
    ref: main
    refresh: 1s
